name: dhis2_flutter_toolkit
description: "A collection of tools and utilities for interacting with DHIS2 authentication, Metadata, and Tracker data"
version: 0.0.6
homepage:

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  connectivity_plus: ^5.0.2
  dart_date: ^1.3.2
  dhis2_flutter_ui: ^1.1.9
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  objectbox: ^2.5.1
  objectbox_flutter_libs: ^2.5.1
  path_provider: ^2.1.2
  provider: ^6.1.2
  syncfusion_flutter_datepicker: ^24.2.9

  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  objectbox_generator: ^2.5.1
  build_runner: ^2.4.8

flutter:
